### ISSUE TITLE
Can't yarn install the library

### ISSUE THREAD

**Issue by minuitagency** [dxFeed/dxfeed-js-api#2]
Hi, 

Thanks for the library, 

When trying to install with yarn, I get the following error: 

`error An unexpected error occurred: "https://registry.yarnpkg.com/@dxfeed%2fcometd: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/theo/springbox/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
`

Thanks, 

Théo

**Comment by VitaliyMatveev** [comment]
Hi,
thanks for your feedback, we will check and get back to you with an answer tomorrow

**Comment by Fyzu** [comment]
Hi, @minuitagency 
You can try again?

**Comment by Fyzu** [comment]
To install the latest version use the command

```sh
yarn add @dxfeed/api
```
