### ISSUE TITLE
NoT working on Nodejs

### ISSUE THREAD

**Issue by metinkun** [dxFeed/dxfeed-js-api#32]
not working on nodejs i am getting this error 
```
node_modules/cometd/cometd.js:3573
        if (window.WebSocket) {
        ^

ReferenceError: window is not defined
```

**Comment by Fyzu** [comment]
@metinkun check the readme, we have updated the part on how to run it on nodejs
Also, you can look at NodeJS example: https://github.com/dxFeed/dxfeed-js-api/blob/master/examples/nodejs-candles.cjs
